# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/pb/service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='models/pb/service.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17models/pb/service.proto\x12\x02pb\"1\n\x0ePredictRequest\x12\x1f\n\x06images\x18\x01 \x03(\x0b\x32\x0f.pb.ImageVector\"\x1d\n\x0bImageVector\x12\x0e\n\x06vector\x18\x01 \x03(\x05\"\x1e\n\x0cPredictReply\x12\x0e\n\x06labels\x18\x01 \x03(\t2<\n\x07Service\x12\x31\n\x07Predict\x12\x12.pb.PredictRequest\x1a\x10.pb.PredictReply\"\x00\x62\x06proto3'
)




_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='pb.PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='pb.PredictRequest.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=80,
)


_IMAGEVECTOR = _descriptor.Descriptor(
  name='ImageVector',
  full_name='pb.ImageVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='pb.ImageVector.vector', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=111,
)


_PREDICTREPLY = _descriptor.Descriptor(
  name='PredictReply',
  full_name='pb.PredictReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='pb.PredictReply.labels', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=143,
)

_PREDICTREQUEST.fields_by_name['images'].message_type = _IMAGEVECTOR
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['ImageVector'] = _IMAGEVECTOR
DESCRIPTOR.message_types_by_name['PredictReply'] = _PREDICTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'models.pb.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)

ImageVector = _reflection.GeneratedProtocolMessageType('ImageVector', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEVECTOR,
  '__module__' : 'models.pb.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.ImageVector)
  })
_sym_db.RegisterMessage(ImageVector)

PredictReply = _reflection.GeneratedProtocolMessageType('PredictReply', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREPLY,
  '__module__' : 'models.pb.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.PredictReply)
  })
_sym_db.RegisterMessage(PredictReply)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='pb.Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=145,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='pb.Service.Predict',
    index=0,
    containing_service=None,
    input_type=_PREDICTREQUEST,
    output_type=_PREDICTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
