
# task is a build-tool created for Go called task
# documentation: https://taskfile.dev/

version: '3'

tasks:
  default:
    deps:
      - task: build

  build:
    cmds:
      - go build ./...

  test:
    cmds:
      - go test ./... 

  protoc:
    # to create go stubs for a proto file <file> perform `$ proto=<file> task protoc`
    cmds:
      - protoc --go_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config:. --go-grpc_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config:. {{.proto}}   --go_opt=paths=source_relative   --go-grpc_opt=paths=source_relative 
      # - protoc --plugin=protoc-gen-go-grpc=$GOBIN/protoc-gen-go-grpc {{.proto}}/receiver.proto --go_out=.
  
  python-protoc:
    cmds:
      - python -m grpc_tools.protoc -I. --grpc_python_out=. --python_out=. {{.proto}}
  
  build-model-containers:
    # Add other dockerfile locations below
    cmds:
      - sudo docker build -t tf-seq-model models/tensorflow/model

