// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package container_models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

var servicePredictStreamDesc = &grpc.StreamDesc{
	StreamName: "Predict",
}

func (c *serviceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error) {
	out := new(PredictReply)
	err := c.cc.Invoke(ctx, "/container_models.Service/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceService is the service API for Service service.
// Fields should be assigned to their respective handler implementations only before
// RegisterServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type ServiceService struct {
	Predict func(context.Context, *PredictRequest) (*PredictReply, error)
}

func (s *ServiceService) predict(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/container_models.Service/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterServiceService registers a service implementation with a gRPC server.
func RegisterServiceService(s grpc.ServiceRegistrar, srv *ServiceService) {
	srvCopy := *srv
	if srvCopy.Predict == nil {
		srvCopy.Predict = func(context.Context, *PredictRequest) (*PredictReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "container_models.Service",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Predict",
				Handler:    srvCopy.predict,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "models/container_models/service.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewServiceService creates a new ServiceService containing the
// implemented methods of the Service service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewServiceService(s interface{}) *ServiceService {
	ns := &ServiceService{}
	if h, ok := s.(interface {
		Predict(context.Context, *PredictRequest) (*PredictReply, error)
	}); ok {
		ns.Predict = h.Predict
	}
	return ns
}

// UnstableServiceService is the service API for Service service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableServiceService interface {
	Predict(context.Context, *PredictRequest) (*PredictReply, error)
}
