// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AbstractionServiceClient is the client API for AbstractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AbstractionServiceClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error)
}

type abstractionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAbstractionServiceClient(cc grpc.ClientConnInterface) AbstractionServiceClient {
	return &abstractionServiceClient{cc}
}

var abstractionServicePredictStreamDesc = &grpc.StreamDesc{
	StreamName: "Predict",
}

func (c *abstractionServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error) {
	out := new(PredictReply)
	err := c.cc.Invoke(ctx, "/pb.AbstractionService/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AbstractionServiceService is the service API for AbstractionService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterAbstractionServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type AbstractionServiceService struct {
	Predict func(context.Context, *PredictRequest) (*PredictReply, error)
}

func (s *AbstractionServiceService) predict(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/pb.AbstractionService/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterAbstractionServiceService registers a service implementation with a gRPC server.
func RegisterAbstractionServiceService(s grpc.ServiceRegistrar, srv *AbstractionServiceService) {
	srvCopy := *srv
	if srvCopy.Predict == nil {
		srvCopy.Predict = func(context.Context, *PredictRequest) (*PredictReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "pb.AbstractionService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Predict",
				Handler:    srvCopy.predict,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "abstraction_service/pb/receiver.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewAbstractionServiceService creates a new AbstractionServiceService containing the
// implemented methods of the AbstractionService service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewAbstractionServiceService(s interface{}) *AbstractionServiceService {
	ns := &AbstractionServiceService{}
	if h, ok := s.(interface {
		Predict(context.Context, *PredictRequest) (*PredictReply, error)
	}); ok {
		ns.Predict = h.Predict
	}
	return ns
}

// UnstableAbstractionServiceService is the service API for AbstractionService service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableAbstractionServiceService interface {
	Predict(context.Context, *PredictRequest) (*PredictReply, error)
}
