// Code generated by protoc-gen-go. DO NOT EDIT.
// source: abstraction_service/pb/receiver.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PredictSetupRequest struct {
	ImageLayers          uint32   `protobuf:"varint,1,opt,name=imageLayers,proto3" json:"imageLayers,omitempty"`
	ImageWidth           uint32   `protobuf:"varint,2,opt,name=imageWidth,proto3" json:"imageWidth,omitempty"`
	ImageHeight          uint32   `protobuf:"varint,3,opt,name=imageHeight,proto3" json:"imageHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictSetupRequest) Reset()         { *m = PredictSetupRequest{} }
func (m *PredictSetupRequest) String() string { return proto.CompactTextString(m) }
func (*PredictSetupRequest) ProtoMessage()    {}
func (*PredictSetupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_307994286c2b9491, []int{0}
}

func (m *PredictSetupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictSetupRequest.Unmarshal(m, b)
}
func (m *PredictSetupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictSetupRequest.Marshal(b, m, deterministic)
}
func (m *PredictSetupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictSetupRequest.Merge(m, src)
}
func (m *PredictSetupRequest) XXX_Size() int {
	return xxx_messageInfo_PredictSetupRequest.Size(m)
}
func (m *PredictSetupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictSetupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictSetupRequest proto.InternalMessageInfo

func (m *PredictSetupRequest) GetImageLayers() uint32 {
	if m != nil {
		return m.ImageLayers
	}
	return 0
}

func (m *PredictSetupRequest) GetImageWidth() uint32 {
	if m != nil {
		return m.ImageWidth
	}
	return 0
}

func (m *PredictSetupRequest) GetImageHeight() uint32 {
	if m != nil {
		return m.ImageHeight
	}
	return 0
}

// in the future we may want to return some data
type PredictSetupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictSetupReply) Reset()         { *m = PredictSetupReply{} }
func (m *PredictSetupReply) String() string { return proto.CompactTextString(m) }
func (*PredictSetupReply) ProtoMessage()    {}
func (*PredictSetupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_307994286c2b9491, []int{1}
}

func (m *PredictSetupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictSetupReply.Unmarshal(m, b)
}
func (m *PredictSetupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictSetupReply.Marshal(b, m, deterministic)
}
func (m *PredictSetupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictSetupReply.Merge(m, src)
}
func (m *PredictSetupReply) XXX_Size() int {
	return xxx_messageInfo_PredictSetupReply.Size(m)
}
func (m *PredictSetupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictSetupReply.DiscardUnknown(m)
}

var xxx_messageInfo_PredictSetupReply proto.InternalMessageInfo

type Pixel struct {
	Layer                uint32   `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Row                  uint32   `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Col                  uint32   `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	Val                  uint32   `protobuf:"varint,4,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pixel) Reset()         { *m = Pixel{} }
func (m *Pixel) String() string { return proto.CompactTextString(m) }
func (*Pixel) ProtoMessage()    {}
func (*Pixel) Descriptor() ([]byte, []int) {
	return fileDescriptor_307994286c2b9491, []int{2}
}

func (m *Pixel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pixel.Unmarshal(m, b)
}
func (m *Pixel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pixel.Marshal(b, m, deterministic)
}
func (m *Pixel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pixel.Merge(m, src)
}
func (m *Pixel) XXX_Size() int {
	return xxx_messageInfo_Pixel.Size(m)
}
func (m *Pixel) XXX_DiscardUnknown() {
	xxx_messageInfo_Pixel.DiscardUnknown(m)
}

var xxx_messageInfo_Pixel proto.InternalMessageInfo

func (m *Pixel) GetLayer() uint32 {
	if m != nil {
		return m.Layer
	}
	return 0
}

func (m *Pixel) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Pixel) GetCol() uint32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *Pixel) GetVal() uint32 {
	if m != nil {
		return m.Val
	}
	return 0
}

// in the future we may want to return some data
type PredictReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictReply) Reset()         { *m = PredictReply{} }
func (m *PredictReply) String() string { return proto.CompactTextString(m) }
func (*PredictReply) ProtoMessage()    {}
func (*PredictReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_307994286c2b9491, []int{3}
}

func (m *PredictReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictReply.Unmarshal(m, b)
}
func (m *PredictReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictReply.Marshal(b, m, deterministic)
}
func (m *PredictReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictReply.Merge(m, src)
}
func (m *PredictReply) XXX_Size() int {
	return xxx_messageInfo_PredictReply.Size(m)
}
func (m *PredictReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictReply.DiscardUnknown(m)
}

var xxx_messageInfo_PredictReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PredictSetupRequest)(nil), "pb.PredictSetupRequest")
	proto.RegisterType((*PredictSetupReply)(nil), "pb.PredictSetupReply")
	proto.RegisterType((*Pixel)(nil), "pb.Pixel")
	proto.RegisterType((*PredictReply)(nil), "pb.PredictReply")
}

func init() {
	proto.RegisterFile("abstraction_service/pb/receiver.proto", fileDescriptor_307994286c2b9491)
}

var fileDescriptor_307994286c2b9491 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xdd, 0xfe, 0x51, 0x1c, 0xff, 0x50, 0xa7, 0x8a, 0x4b, 0x0f, 0x52, 0x16, 0x84, 0xe2,
	0x61, 0x0b, 0xfa, 0x05, 0xd4, 0x93, 0x07, 0x0f, 0xa5, 0x7b, 0x10, 0xbc, 0x48, 0x92, 0x0e, 0x6d,
	0x20, 0x9a, 0x98, 0x4d, 0x57, 0xf7, 0xea, 0x27, 0xb7, 0xc9, 0x86, 0xba, 0xa2, 0xb7, 0x99, 0xdf,
	0x3e, 0xde, 0x9b, 0x7d, 0x81, 0x4b, 0xc6, 0x4b, 0x67, 0x99, 0x70, 0x52, 0xbf, 0xbd, 0x94, 0x64,
	0x2b, 0x29, 0x68, 0x6a, 0xf8, 0xd4, 0x92, 0x20, 0x59, 0x91, 0xcd, 0x8d, 0xd5, 0x4e, 0x63, 0xc7,
	0xf0, 0xac, 0x86, 0xe1, 0xcc, 0xd2, 0x42, 0x0a, 0x57, 0x90, 0x5b, 0x9b, 0x39, 0xbd, 0xaf, 0xa9,
	0x74, 0x38, 0x86, 0x03, 0xf9, 0xca, 0x96, 0xf4, 0xc8, 0x6a, 0xb2, 0x65, 0x9a, 0x8c, 0x93, 0xc9,
	0xd1, 0xbc, 0x8d, 0xf0, 0x02, 0x20, 0xac, 0x4f, 0x72, 0xe1, 0x56, 0x69, 0x27, 0x08, 0x5a, 0x64,
	0xeb, 0xf0, 0x40, 0x72, 0xb9, 0x72, 0x69, 0xb7, 0xe5, 0xd0, 0xa0, 0x6c, 0x08, 0x27, 0xbf, 0xa3,
	0x8d, 0xaa, 0xb3, 0x02, 0xfa, 0x33, 0xf9, 0x49, 0x0a, 0x4f, 0xa1, 0xaf, 0x7c, 0x52, 0xcc, 0x6e,
	0x16, 0x1c, 0x40, 0xd7, 0xea, 0x8f, 0x18, 0xe7, 0x47, 0x4f, 0x84, 0x56, 0xd1, 0xdf, 0x8f, 0x9e,
	0x54, 0x4c, 0xa5, 0xbd, 0x86, 0x6c, 0xc6, 0xec, 0x18, 0x0e, 0x63, 0x52, 0x08, 0xb9, 0xfe, 0x4a,
	0x00, 0xef, 0x7e, 0x2a, 0x2a, 0x9a, 0x86, 0xf0, 0x76, 0x2b, 0x0b, 0x07, 0xe1, 0x79, 0x6e, 0x78,
	0xfe, 0x4f, 0x3b, 0xa3, 0xb3, 0xbf, 0x1f, 0xfc, 0xed, 0x3b, 0x78, 0x05, 0x7b, 0x11, 0xe3, 0x7e,
	0xd0, 0xf8, 0x5f, 0x19, 0x0d, 0x5a, 0xf2, 0xa8, 0x9c, 0x24, 0xf7, 0xbd, 0xe7, 0x4d, 0xff, 0x7c,
	0x37, 0x3c, 0xc5, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x3e, 0x2a, 0xe3, 0xb3, 0x01,
	0x00, 0x00,
}
